/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBlankAiRouteImport } from './routes/api/blank-ai'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlankAiRoute = ApiBlankAiRouteImport.update({
  id: '/api/blank-ai',
  path: '/api/blank-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/store': typeof StoreRoute
  '/api/blank-ai': typeof ApiBlankAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/store': typeof StoreRoute
  '/api/blank-ai': typeof ApiBlankAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/store': typeof StoreRoute
  '/api/blank-ai': typeof ApiBlankAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/store' | '/api/blank-ai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/store' | '/api/blank-ai'
  id: '__root__' | '/' | '/store' | '/api/blank-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreRoute: typeof StoreRoute
  ApiBlankAiRoute: typeof ApiBlankAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blank-ai': {
      id: '/api/blank-ai'
      path: '/api/blank-ai'
      fullPath: '/api/blank-ai'
      preLoaderRoute: typeof ApiBlankAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreRoute: StoreRoute,
  ApiBlankAiRoute: ApiBlankAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
